---  
- name: Update apt cache
  apt: update_cache=yes cache_valid_time={{apt_cache_timeout}}
  tags: bootstrap

- name: create group
  group:
    name: zookeeper
    state: present
  tags: zookeeper

- name: create user
  user:
    name: zookeeper
    group: zookeeper
  tags: zookeeper

- name: Setting internal variable
  set_fact:
    zookeeper_name: apache-zookeeper-{{ zookeeper.version }}-bin
  tags: zookeeper

- name: Download Zookeeper {{ zookeeper.version }}
  get_url:
    url: "{{ zookeeper.mirror }}/zookeeper/zookeeper-{{ zookeeper.version }}/{{ zookeeper_name }}.tar.gz"
    dest: "{{ zookeeper.download_dir }}/{{ zookeeper_name }}.tar.gz"
    mode: 0644
    force: no
  tags: zookeeper

- name: Unpack the tar
  shell: tar -xzvf {{ zookeeper.download_dir }}/{{ zookeeper_name }}.tar.gz chdir={{ zookeeper.download_dir }}/ creates={{ zookeeper.download_dir }}/{{ zookeeper_name }}
  tags: zookeeper

- name: Copy zookeeper to real destination
  shell: mv {{ zookeeper.download_dir }}/{{ zookeeper_name }} {{ zookeeper_dir }} creates={{ zookeeper_dir }}
  tags: zookeeper

######
- name: ensure the data subdir exists
  become: yes
  become_user: root
  file:
    path: '{{ zookeeper_data_dir }}'
    state: directory
    mode: 0700
  tags: zookeeper

- name: configuring zookeeper
  become: yes
  become_user: root
  with_items:
    - f: zoo.cfg
      d: '{{ zookeeper_conf_dir }}'
    - f: log4j.properties
      d: '{{ zookeeper_conf_dir }}'
    - f: myid
      d: '{{ zookeeper_data_dir }}'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
  tags: zookeeper

- name: configurating init system
  include_tasks: '{{ zookeeper_init_system|default(systemd) }}.yml'
  tags: zookeeper

